2017-09-28 15:54:12,479 > ERROR > snmp_sys_uptime
Traceback (most recent call last):
  File "/home/networksnap/share/projects/network_snap/nmv1.py", line 22, in snmp_sys_uptime
    uptime = ses.get('.1.3.6.1.2.1.1.3.0').value
AttributeError: 'tuple' object has no attribute 'get'
2017-09-28 15:54:21,653 > ERROR > snmp_sys_uptime
Traceback (most recent call last):
  File "/home/networksnap/share/projects/network_snap/nmv1.py", line 22, in snmp_sys_uptime
    uptime = ses.get('.1.3.6.1.2.1.1.3.0').value
AttributeError: 'tuple' object has no attribute 'get'
2017-09-28 15:59:22,243 > ERROR > snmp_sys_uptime
Traceback (most recent call last):
  File "/home/networksnap/share/projects/network_snap/nmv1.py", line 22, in snmp_sys_uptime
    uptime = ses.get('.1.3.6.1.2.1.1.3.0').value
AttributeError: 'tuple' object has no attribute 'get'
2017-09-28 15:59:31,312 > ERROR > snmp_sys_uptime
Traceback (most recent call last):
  File "/home/networksnap/share/projects/network_snap/nmv1.py", line 22, in snmp_sys_uptime
    uptime = ses.get('.1.3.6.1.2.1.1.3.0').value
AttributeError: 'tuple' object has no attribute 'get'
2017-10-01 06:15:05,048 > ERROR > cis_bgp Ex2
Traceback (most recent call last):
  File "/home/networksnap/network_snap/nmv1.py", line 319, in cis_bgp
    mon_ = mon_.split(",")
AttributeError: 'NoneType' object has no attribute 'split'
